### ISSUE TITLE
Rename everything that has prefix AP

### ISSUE THREAD

**Issue by AmerPandzo** [AmerPandzo/ap_sellmap#2]
We need to rename everything (controllers, services, comments , routes) that has prefix Ap, to without Ap.

**Comment by bhaskarmac** [comment]
@AmerPandzo  I would like to work on this, I will be taking this Issue.

**Comment by jespicas** [comment]
Pull-request has created after you take this, sorry to not inform. I have no experience I did not know that this was the operation

**Comment by AmerPandzo** [comment]
@bhaskarmac You can take this too , since the issue was to rename controller, services etc , @jespicas only renamed files names.

**Comment by bhaskarmac** [comment]
@AmerPandzo Sure

**Comment by bhaskarmac** [comment]
@AmerPandzo  Could you please merge the PR #3  into master so that I can start working next

**Comment by AmerPandzo** [comment]
@bhaskarmac merged
